(()=>{"use strict";
const api="https://iuhotznurbyujzbyhizf.supabase.co/rest/v1/content_media";
const key="sb_publishable_bpAZ5EhYLIuVoE4Q97s_-A_XQwwRxUj";
const style=document.createElement("style");
style.textContent=`
.as-media{box-sizing:border-box;margin:42px 0 28px;padding:0;background:transparent!important;color:var(--paper,#eee6d8)!important;border:0!important;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.55}
.as-media *{box-sizing:border-box}
.as-media-head{border-top:1px solid rgba(168,140,85,.55);border-bottom:1px solid rgba(168,140,85,.22);padding:19px 0 18px;margin-bottom:7px}
.as-media-kicker{font:500 10px/1.4 var(--font-mono,monospace)!important;color:var(--gold-light,#c4aa70)!important;letter-spacing:.19em}
.as-media h2{font:500 clamp(20px,3vw,27px)/1.3 var(--font-display,Georgia,serif)!important;letter-spacing:.055em!important;color:var(--paper,#eee6d8)!important;margin:7px 0 6px!important}
.as-media-intro{font:400 13px/1.65 Arial,sans-serif!important;color:var(--paper-soft,#c9beae)!important;margin:0!important;max-width:620px}
.as-media article{display:grid!important;grid-template-columns:106px minmax(0,1fr);gap:20px!important;align-items:start!important;padding:25px 0!important;margin:0!important;border:0!important;border-bottom:1px solid rgba(168,140,85,.19)!important;background:transparent!important}
.as-media-cover{width:106px;height:157px;object-fit:cover;border:1px solid rgba(168,140,85,.3);background:#211c18;display:block;box-shadow:0 4px 16px rgba(0,0,0,.3)}
.as-media-cover-placeholder{width:106px;height:157px;border:1px solid rgba(168,140,85,.35);background:linear-gradient(150deg,#211b18,#110e0d);display:grid;place-content:center;text-align:center;color:#a88c55;font:11px var(--font-mono,monospace);letter-spacing:.12em}
.as-media-body{min-width:0}
.as-media small{display:block;font:500 10px/1.4 var(--font-mono,monospace)!important;letter-spacing:.11em;color:var(--gold-light,#c4aa70)!important;margin:1px 0 9px}
.as-media h3{font:500 clamp(17px,2.6vw,21px)/1.35 var(--font-display,Georgia,serif)!important;color:var(--paper,#eee6d8)!important;margin:0 0 9px!important;letter-spacing:0!important}
.as-media .as-media-description{font:400 13px/1.65 Arial,Helvetica,sans-serif!important;color:var(--paper-soft,#c9beae)!important;margin:0 0 12px!important;max-width:640px}
.as-media .as-media-rating{font:11px var(--font-mono,monospace)!important;color:var(--gold-light,#c4aa70)!important;margin:0 0 8px!important}
.as-media .as-media-links{display:flex;flex-wrap:wrap;gap:8px}
.as-media .as-media-links a{display:inline-flex!important;align-items:center;justify-content:center;min-height:32px;padding:6px 11px!important;border:1px solid rgba(168,140,85,.38)!important;border-radius:2px;background:rgba(168,140,85,.055)!important;color:var(--paper,#eee6d8)!important;text-decoration:none!important;font:500 10px/1.4 var(--font-mono,monospace)!important;letter-spacing:.04em;margin:0!important;transition:background .2s,border-color .2s}
.as-media .as-media-links a:hover,.as-media .as-media-links a:focus-visible{background:rgba(168,140,85,.16)!important;border-color:#c4aa70!important}
@media(max-width:520px){.as-media{margin:28px 0}.as-media article{grid-template-columns:82px minmax(0,1fr);gap:13px!important;padding:20px 0!important}.as-media-cover,.as-media-cover-placeholder{width:82px;height:122px}.as-media h3{font-size:17px!important}.as-media .as-media-description{font-size:12px!important}.as-media .as-media-links a{font-size:9px!important}}
`;document.head.append(style);
function link(parent,url,label,affiliate){if(!url||!url.startsWith("https://"))return;const a=document.createElement("a");a.href=url;a.textContent=label;a.target="_blank";a.rel=affiliate?"sponsored noopener noreferrer":"noopener noreferrer";parent.append(a)}
let pending=false;async function render(type,id,anchor){if(!id||!anchor||pending||anchor.querySelector(".as-media"))return;pending=true;try{const res=await fetch(api+"?select=*&content_type=eq."+type+"&content_id=eq."+id+"&status=eq.publicado&order=sort_order.asc",{headers:{apikey:key}});if(!res.ok)return;const items=await res.json();if(!items.length)return;const section=document.createElement("section");section.className="as-media";const head=document.createElement("header");head.className="as-media-head";const kicker=document.createElement("span");kicker.className="as-media-kicker";kicker.textContent="ACERVO COMPLEMENTAR";const h=document.createElement("h2");h.textContent="INFORMAÇÕES DE MÍDIA";const note=document.createElement("p");note.className="as-media-intro";note.textContent="Filmes e livros relacionados ao caso. Adaptações ficcionais não são fontes documentais.";head.append(kicker,h,note);section.append(head);for(const x of items){const a=document.createElement("article");if(x.cover_url?.startsWith("https://")){const img=document.createElement("img");img.className="as-media-cover";img.src=x.cover_url;img.alt="Capa: "+x.title;img.loading="lazy";img.onerror=()=>{const placeholder=document.createElement("div");placeholder.className="as-media-cover-placeholder";placeholder.textContent=x.media_type==="livro"?"LIVRO":"FILME";img.replaceWith(placeholder)};a.append(img)}else{const placeholder=document.createElement("div");placeholder.className="as-media-cover-placeholder";placeholder.textContent=x.media_type==="livro"?"LIVRO":"FILME";a.append(placeholder)}const b=document.createElement("div");const small=document.createElement("small");small.textContent=x.media_type.toUpperCase()+" · "+(x.relation_type==="inspirado"?"FICÇÃO INSPIRADA":"OBRA RELACIONADA");const title=document.createElement("h3");title.textContent=x.title+(x.release_year?" ("+x.release_year+")":"");const p=document.createElement("p");p.className="as-media-description";p.textContent=x.synopsis;b.append(small,title,p);const links=document.createElement("div");links.className="as-media-links";if(x.imdb_rating!=null){const t=document.createElement("p");t.className="as-media-rating";t.textContent="IMDb: "+x.imdb_rating+"/10";b.append(t)}if(x.goodreads_rating!=null){const t=document.createElement("p");t.className="as-media-rating";t.textContent="Goodreads: "+x.goodreads_rating+"/5";b.append(t)}link(links,x.imdb_url,"VER NO IMDb ↗");link(links,x.goodreads_url,"GOODREADS ↗");link(links,x.watch_url,x.watch_label||"ONDE ASSISTIR ↗");link(links,x.affiliate_url,"COMPRAR · AFILIADO ↗",true);b.append(links);a.append(b);section.append(a)}{const article=type==="garimpo"?anchor.querySelector(".daily-reader"):null;(article||anchor).append(section)}}catch(e){console.warn("Media indisponivel",e)}finally{pending=false}}
function init(){const params=new URLSearchParams(location.search),id=Number(params.get("id"));if(!Number.isSafeInteger(id)||id<1)return;const garimpo=location.pathname.includes("garimpo");const target=garimpo?document.getElementById("daily-case-detail"):document.querySelector("main");if(!target)return;if(garimpo){const observer=new MutationObserver(()=>{if(target.querySelector(".daily-reader")&&!target.querySelector(".as-media"))render("garimpo",id,target)});observer.observe(target,{childList:true});if(target.querySelector(".daily-reader"))render("garimpo",id,target)}else render("dossie",id,target)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();