"use strict";
const SUPABASE_URL="https://iuhotznurbyujzbyhizf.supabase.co",KEY="sb_publishable_bpAZ5EhYLIuVoE4Q97s_-A_XQwwRxUj";
const sb=window.supabase.createClient(SUPABASE_URL,KEY);
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const slug=new URLSearchParams(location.search).get("obra"),cap=Number(new URLSearchParams(location.search).get("capitulo")||0);
function cover(x,cl="novel-cover"){return x.imagem_capa?'<img class="'+cl+'" src="'+esc(x.imagem_capa)+'" alt="Capa de '+esc(x.titulo)+'">':'<div class="'+cl+'"></div>'}
async function catalog(){const root=document.querySelector("#novel-grid");if(!root)return;const {data,error}=await sb.from("novels").select("*").eq("status_publicacao","publicado").order("destaque",{ascending:false}).order("publicado_em",{ascending:false});if(error){root.innerHTML='<p class="empty">Não foi possível carregar o acervo.</p>';return}const input=document.querySelector("#novel-search"),genre=document.querySelector("#novel-genre");const gs=[...new Set(data.flatMap(x=>x.generos||[]))].sort();genre.innerHTML='<option value="">Todos os gêneros</option>'+gs.map(g=>'<option>'+esc(g)+'</option>').join("");const draw=()=>{const q=(input.value||"").toLowerCase(),g=genre.value;const rows=data.filter(x=>(!q||[x.titulo,x.autor_nome,x.sinopse,...(x.tags||[])].join(" ").toLowerCase().includes(q))&&(!g||(x.generos||[]).includes(g)));root.innerHTML=rows.map(x=>'<a class="novel-card" href="novel.html?obra='+encodeURIComponent(x.slug)+'">'+cover(x)+'<h2>'+esc(x.titulo)+'</h2><p>'+esc(x.autor_nome)+' · '+esc(x.status_obra.replaceAll("_"," "))+'</p><div class="novel-tags">'+(x.generos||[]).slice(0,3).map(t=>'<span>'+esc(t)+'</span>').join("")+'</div></a>').join("")||'<p class="empty">Nenhuma obra encontrada.</p>'};input.oninput=draw;genre.onchange=draw;draw()}
async function detail(){const root=document.querySelector("#novel-detail");if(!root||!slug||cap)return;root.hidden=false;const {data:n}=await sb.from("novels").select("*").eq("slug",slug).eq("status_publicacao","publicado").single();if(!n){root.innerHTML='<p class="empty">Obra não encontrada.</p>';return}const {data:chs}=await sb.from("novel_capitulos").select("id,numero,titulo,palavras,publicado_em").eq("novel_id",n.id).eq("status_publicacao","publicado").order("numero");document.title=n.titulo+" — Novels · Arquivo Sombrio";root.innerHTML='<div>'+cover(n,"novel-detail-cover")+'</div><div><p class="novel-kicker">NOVEL · '+esc(n.status_obra.replaceAll("_"," ").toUpperCase())+'</p><h1>'+esc(n.titulo)+'</h1><p>'+esc(n.autor_nome)+'</p><div class="novel-tags">'+(n.generos||[]).map(t=>'<span>'+esc(t)+'</span>').join("")+'</div><p class="novel-synopsis">'+esc(n.sinopse)+'</p>'+(chs?.length?'<a class="novel-button" href="novel.html?obra='+encodeURIComponent(slug)+'&capitulo='+chs[0].numero+'">Começar a ler</a><button class="novel-button" id="novel-library-toggle" type="button">Adicionar às minhas leituras</button>':'')+'<section class="chapter-area"><h2>Capítulos</h2><div class="chapter-list">'+(chs||[]).map(c=>'<a class="chapter-link" href="novel.html?obra='+encodeURIComponent(slug)+'&capitulo='+c.numero+'"><span>Capítulo '+c.numero+' · '+esc(c.titulo)+'</span><small>'+c.palavras+' palavras</small></a>').join("")+'</div></section></div>';const {data:{user}}=await sb.auth.getUser();const toggle=document.querySelector("#novel-library-toggle");if(toggle&&user){const {data:saved}=await sb.from("novel_biblioteca").select("novel_id").eq("user_id",user.id).eq("novel_id",n.id).maybeSingle();let active=!!saved;const label=()=>toggle.textContent=active?"Remover das minhas leituras":"Adicionar às minhas leituras";label();toggle.onclick=async()=>{if(active){const {error}=await sb.from("novel_biblioteca").delete().eq("user_id",user.id).eq("novel_id",n.id);if(!error)active=false}else{const {error}=await sb.from("novel_biblioteca").insert({user_id:user.id,novel_id:n.id,estado:"acompanhando"});if(!error)active=true}label()}}else if(toggle){toggle.onclick=()=>location.href="meu-arquivo.html"}}
async function reader(){const root=document.querySelector("#novel-reader");if(!root||!slug||!cap)return;const detailRoot=document.querySelector("#novel-detail");if(detailRoot)detailRoot.hidden=true;const {data:n}=await sb.from("novels").select("id,titulo,slug").eq("slug",slug).eq("status_publicacao","publicado").single();if(!n){root.hidden=false;root.innerHTML='<p class="empty">Obra indisponível.</p>';return;}const {data:chs}=await sb.from("novel_capitulos").select("id,numero,titulo,conteudo").eq("novel_id",n.id).eq("status_publicacao","publicado").order("numero");const i=chs.findIndex(x=>x.numero===cap),c=chs[i];if(!c){root.innerHTML='<p class="empty">Capítulo não encontrado.</p>';return}document.querySelector("#novel-detail").hidden=true;root.hidden=false;document.title="Capítulo "+c.numero+" · "+n.titulo;const body=esc(c.conteudo).split(/\n\s*\n/).filter(Boolean).map(p=>"<p>"+p.replaceAll("\n","<br>")+"</p>").join("");root.innerHTML='<a class="novel-home" href="novel.html?obra='+encodeURIComponent(slug)+'">← '+esc(n.titulo)+'</a><p class="novel-kicker">CAPÍTULO '+c.numero+'</p><h1>'+esc(c.titulo)+'</h1><div class="reader-settings"><label for="chapter-jump">Capítulo</label><select id="chapter-jump" aria-label="Ir para capítulo">'+chs.map(ch=>'<option value="'+ch.numero+'"'+(ch.numero===c.numero?' selected':'')+'>'+ch.numero+' · '+esc(ch.titulo)+'</option>').join('')+'</select><button id="font-down">A−</button><button id="font-up">A+</button></div><article class="reader-body" id="reader-body">'+body+'</article><nav class="reader-nav">'+(chs[i-1]?'<a class="novel-home" href="novel.html?obra='+encodeURIComponent(slug)+'&capitulo='+chs[i-1].numero+'">← Anterior</a>':'<span></span>')+(chs[i+1]?'<a class="novel-home" href="novel.html?obra='+encodeURIComponent(slug)+'&capitulo='+chs[i+1].numero+'">Próximo →</a>':'<span>Fim disponível</span>')+'</nav>';document.querySelector("#chapter-jump").onchange=e=>{location.href="novel.html?obra="+encodeURIComponent(slug)+"&capitulo="+encodeURIComponent(e.target.value)};const prefsKey="as-novel-reader-v1";
const defaults={theme:"archive",font:"Georgia",size:1.16,spacing:"comfortable",immersive:false};
let prefs;
try{prefs={...defaults,...JSON.parse(localStorage.getItem(prefsKey)||"{}")}}catch{prefs={...defaults}}
const themes=["archive","paper","night"],fonts=["Georgia","Verdana","Arial"],spacings=["compact","comfortable","wide"];
if(!themes.includes(prefs.theme))prefs.theme=defaults.theme;
if(!fonts.includes(prefs.font))prefs.font=defaults.font;
if(!spacings.includes(prefs.spacing))prefs.spacing=defaults.spacing;
prefs.size=Math.max(.95,Math.min(1.65,Number(prefs.size)||defaults.size));
const settings=document.querySelector(".reader-settings");
settings.insertAdjacentHTML("beforeend",'<button type="button" id="reader-options" aria-expanded="false" aria-controls="reader-preferences">Aa · Aparência</button><button type="button" id="reader-immersive" aria-pressed="false">Modo imersivo</button>');
settings.insertAdjacentHTML("afterend",'<section id="reader-preferences" class="reader-preferences" hidden aria-label="Preferências de leitura"><div class="reader-pref-row"><span>Tema</span><div role="group" aria-label="Tema"><button data-reader-theme="archive">Arquivo</button><button data-reader-theme="paper">Papel antigo</button><button data-reader-theme="night">Noturno</button></div></div><div class="reader-pref-row"><label for="reader-font">Fonte</label><select id="reader-font"><option>Georgia</option><option>Verdana</option><option>Arial</option></select></div><div class="reader-pref-row"><label for="reader-spacing">Espaçamento</label><select id="reader-spacing"><option value="compact">Compacto</option><option value="comfortable">Confortável</option><option value="wide">Amplo</option></select></div><button type="button" id="reader-reset">Restaurar padrão</button></section>');
const panel=document.querySelector("#reader-preferences"),bodyEl=document.querySelector("#reader-body"),immersiveButton=document.querySelector("#reader-immersive");
const persist=()=>{try{localStorage.setItem(prefsKey,JSON.stringify(prefs))}catch{}};
const apply=()=>{document.body.dataset.readerTheme=prefs.theme;document.body.classList.toggle("reader-immersive",!!prefs.immersive);bodyEl.style.fontSize=prefs.size+"rem";bodyEl.style.fontFamily=prefs.font+", Georgia, serif";bodyEl.dataset.spacing=prefs.spacing;document.querySelector("#reader-font").value=prefs.font;document.querySelector("#reader-spacing").value=prefs.spacing;document.querySelectorAll("[data-reader-theme]").forEach(b=>b.setAttribute("aria-pressed",String(b.dataset.readerTheme===prefs.theme)));immersiveButton.setAttribute("aria-pressed",String(!!prefs.immersive));immersiveButton.textContent=prefs.immersive?"Sair do modo imersivo":"Modo imersivo";persist()};
document.querySelector("#reader-options").onclick=()=>{panel.hidden=!panel.hidden;document.querySelector("#reader-options").setAttribute("aria-expanded",String(!panel.hidden))};
document.querySelectorAll("[data-reader-theme]").forEach(b=>b.onclick=()=>{prefs.theme=b.dataset.readerTheme;apply()});
document.querySelector("#reader-font").onchange=e=>{prefs.font=e.target.value;apply()};
document.querySelector("#reader-spacing").onchange=e=>{prefs.spacing=e.target.value;apply()};
document.querySelector("#font-up").onclick=()=>{prefs.size=Math.min(1.65,Math.round((prefs.size+.08)*100)/100);apply()};
document.querySelector("#font-down").onclick=()=>{prefs.size=Math.max(.95,Math.round((prefs.size-.08)*100)/100);apply()};
immersiveButton.onclick=()=>{prefs.immersive=!prefs.immersive;apply()};
document.querySelector("#reader-reset").onclick=()=>{prefs={...defaults};apply()};
apply();
const {data:{user}}=await sb.auth.getUser();if(user){const save=()=>{const max=Math.max(1,document.documentElement.scrollHeight-innerHeight),pct=Math.min(100,Math.max(0,scrollY/max*100));sb.from("novel_progresso").upsert({user_id:user.id,novel_id:n.id,capitulo_id:c.id,percentual:pct,scroll_y:Math.round(scrollY)},{onConflict:"user_id,novel_id"}).then(()=>{})};let timer;addEventListener("scroll",()=>{clearTimeout(timer);timer=setTimeout(save,900)},{passive:true});const {data:p}=await sb.from("novel_progresso").select("scroll_y,capitulo_id").eq("user_id",user.id).eq("novel_id",n.id).maybeSingle();if(p?.capitulo_id===c.id&&p?.scroll_y)setTimeout(()=>scrollTo(0,p.scroll_y),150)}}
document.addEventListener("DOMContentLoaded",()=>{for(const [fn,selector] of [[catalog,"#novel-grid"],[detail,"#novel-detail"],[reader,"#novel-reader"]]){Promise.resolve().then(fn).catch(err=>{console.error("Novels:",err);const el=document.querySelector(selector);if(el)el.innerHTML='<div class="novel-notice"><h2>Não foi possível carregar o acervo</h2><p>Verifique sua conexão e tente novamente.</p><button class="novel-button" onclick="location.reload()">Tentar novamente</button></div>'})}});