(function(){
var endpoint="https://iuhotznurbyujzbyhizf.supabase.co/functions/v1/lite-admin",token="",currentId="",updated="",category="dossies",dirty=false;
var types=[["dossies","Dossiês"],["garimpo","Garimpo"],["pericia","Perícia"],["lendas","Lendas"],["creepypastas","Creepypastas"],["novels","Livros"],["capitulos","Capítulos"]];
var fields=["titulo","subtitulo","resumo","situacao","local","data","conteudo","cronologia","evidencias","teorias","contexto","fontes","livro","numero","notas","pendencias"];
function el(id){return document.getElementById(id)}function txt(id,s){el(id).textContent=s}function show(id,yes){el(id).className=yes?el(id).className.replace(/\bhidden\b/g,"").replace(/\s+/g," "):"hidden"}
function esc(s){return String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;/g,"&quot;")}
function request(action,data,cb){var xhr=new XMLHttpRequest();xhr.open("POST",endpoint,true);xhr.setRequestHeader("Content-Type","application/json");xhr.timeout=20000;xhr.onreadystatechange=function(){if(xhr.readyState!==4)return;var v={};try{v=JSON.parse(xhr.responseText)}catch(e){}if(xhr.status===401&&action!=="login"){token="";show("panel",false);show("login",true)}cb(xhr.status,v)};xhr.onerror=function(){cb(0,{error:"Falha de conexão. Verifique o HTTPS e tente novamente."})};xhr.ontimeout=function(){cb(0,{error:"Tempo esgotado"})};var v=data||{};v.action=action;v.token=token;xhr.send(JSON.stringify(v))}
function values(){var v={};for(var i=0;i<fields.length;i++)v[fields[i]]=el(fields[i]).value;return v}
function fill(v){for(var i=0;i<fields.length;i++)el(fields[i]).value=typeof v[fields[i]]==="string"?v[fields[i]]:""}
function changed(){dirty=true;txt("unsaved","Alterações não salvas.")}
for(var i=0;i<fields.length;i++)el(fields[i]).oninput=changed;
function choose(c){if(dirty&&!confirm("Existem alterações não salvas. Deseja trocar de categoria?"))return;category=c;currentId="";updated="";dirty=false;fill({});txt("section-title","Novo rascunho · "+label(c));show("book-fields",c==="novels"||c==="capitulos");var buttons=el("categories").getElementsByTagName("button");for(var i=0;i<buttons.length;i++)buttons[i].className=buttons[i].getAttribute("data-category")===c?"active":"";txt("unsaved","Sem alterações pendentes.")}
function label(c){for(var i=0;i<types.length;i++)if(types[i][0]===c)return types[i][1];return c}
var nav=el("categories");for(var i=0;i<types.length;i++){var b=document.createElement("button");b.type="button";b.setAttribute("data-category",types[i][0]);b.appendChild(document.createTextNode(types[i][1]));b.onclick=function(){choose(this.getAttribute("data-category"))};nav.appendChild(b)}
el("enter").onclick=function(){var password=el("password").value;txt("login-status","Validando acesso...");request("login",{password:password},function(status,v){el("password").value="";if(status===200&&v.token){token=v.token;show("login",false);show("panel",true);choose("dossies");txt("status","Acesso autorizado. Rascunhos apenas.");loadList()}else txt("login-status",v.error||"Não foi possível autenticar.")})};
el("logout").onclick=function(){request("logout",{},function(){});token="";show("panel",false);show("login",true);txt("status","Sessão encerrada.")};
function loadList(){txt("status","Carregando rascunhos...");request("list",{},function(status,v){if(status!==200){txt("status",v.error||"Erro ao carregar");return}var ul=el("drafts");while(ul.firstChild)ul.removeChild(ul.firstChild);var items=v.items||[];for(var i=0;i<items.length;i++){(function(item){var li=document.createElement("li"),b=document.createElement("button");b.type="button";b.appendChild(document.createTextNode(item.title+" · "+label(item.category)));b.onclick=function(){openDraft(item.id)};li.appendChild(b);ul.appendChild(li)})(items[i])}txt("status",items.length+" rascunho(s) disponíveis.")})}
function openDraft(id){if(dirty&&!confirm("Descartar alterações não salvas?"))return;request("get",{id:id},function(status,v){if(status!==200||!v.item){txt("status",v.error||"Não encontrado");return}category=v.item.category;currentId=v.item.id;updated=v.item.updated_at;dirty=false;fill(v.item.payload||{});txt("section-title","Editando · "+v.item.title);show("book-fields",category==="novels"||category==="capitulos");txt("unsaved","Sem alterações pendentes.");txt("status","Rascunho carregado.")})}
el("list").onclick=loadList;el("new").onclick=function(){choose(category)};
el("save").onclick=function(){var v=values();if(!v.titulo.trim()){txt("status","Preencha o título.");return}txt("status","Salvando...");request("save",{id:currentId||null,updated_at:updated||null,category:category,title:v.titulo,payload:v},function(status,r){if(status===200&&r.item){currentId=r.item.id;updated=r.item.updated_at;dirty=false;txt("unsaved","Rascunho remoto salvo.");txt("status","Salvo. Não publicado nem agendado.");loadList()}else txt("status",r.error||"Não foi possível salvar.")})};
el("preview").onclick=function(){var v=values(),html="<h2>"+esc(v.titulo)+"</h2><p>"+esc(v.resumo)+"</p>";for(var i=3;i<fields.length;i++){var k=fields[i];if(v[k])html+="<h3>"+esc(k)+"</h3><p>"+esc(v[k]).replace(/\n/g,"<br>")+"</p>"}el("render").innerHTML=html;show("output",true);location.hash="output"};
el("check").onclick=function(){var v=values(),checks=[["Título",v.titulo.trim()],["Resumo",v.resumo.trim()],["Conteúdo principal",v.conteudo.trim()],["Fontes ou referências",v.fontes.trim()],["Pendências resolvidas",!v.pendencias.trim()]],html="<ul>";for(var i=0;i<checks.length;i++)html+="<li>"+(checks[i][1]?"✓ ":"○ ")+esc(checks[i][0])+"</li>";el("render").innerHTML=html+"</ul>";show("output",true);location.hash="output"};
el("export").onclick=function(){var content=JSON.stringify({category:category,payload:values()},null,2),a=document.createElement("a");a.href="data:application/json;charset=utf-8,"+encodeURIComponent(content);a.download="rascunho-lite.json";document.body.appendChild(a);if(typeof a.download==="string"){a.click();document.body.removeChild(a);txt("status","Verifique se o backup foi salvo.")}else{document.body.removeChild(a);var t=document.createElement("textarea");t.value=content;el("render").innerHTML="";el("render").appendChild(t);show("output",true);txt("status","Copie o texto do backup.")}};
window.onbeforeunload=function(){if(dirty)return "Existem alterações não salvas."};choose("dossies");
})();