import{requireAdmin,loginAdmin,signOut}from"./auth.js";import{NAV,LABELS}from"./navigation.js";import{CONTENT,listContent,dashboardCounts}from"./data.js";import{openDossierEditor}from"./editor-dossie.js";
const login=document.getElementById("admin-v2-login"),app=document.getElementById("admin-v2-app"),nav=document.getElementById("admin-v2-nav"),view=document.getElementById("admin-v2-view"),title=document.getElementById("admin-v2-title");
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));const date=v=>v?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(v)):"—";
function renderNav(){nav.innerHTML=NAV.map(g=>'<div class="admin-nav-group">'+g.group+'</div>'+g.items.map(([id,label])=>'<button class="admin-nav-button" data-view="'+id+'">'+label+'</button>').join("")).join("");nav.onclick=e=>{const b=e.target.closest("[data-view]");if(b)openView(b.dataset.view)}}
async function renderOverview(){view.innerHTML='<div class="admin-placeholder">Carregando dados do Arquivo...</div>';try{const x=await dashboardCounts();view.innerHTML='<div class="admin-notice"><strong>Modo de leitura segura.</strong><br>O V2 consulta dados reais, mas criação, edição, publicação e exclusão permanecem desabilitadas nesta etapa.</div><div class="admin-grid admin-section"><article class="admin-card"><small>Conteúdos no acervo</small><strong>'+x.total+'</strong></article><article class="admin-card"><small>Rascunhos administrativos</small><strong>'+x.drafts+'</strong></article><article class="admin-card"><small>Denúncias pendentes</small><strong>'+x.reports+'</strong></article><article class="admin-card"><small>Sugestões novas</small><strong>'+x.suggestions+'</strong></article></div><section class="admin-section"><h2>Acervo por seção</h2><div class="admin-grid">'+Object.entries(x.content).map(([k,n])=>'<article class="admin-card"><small>'+esc(CONTENT[k].label)+'</small><strong>'+n+'</strong></article>').join("")+'</div></section>'}catch(e){view.innerHTML='<div class="admin-notice">Não foi possível carregar o Dashboard: '+esc(e.message)+'</div>'}}
async function renderContent(id){view.innerHTML='<div class="admin-placeholder">Carregando '+esc(CONTENT[id].label)+'...</div>';try{const rows=await listContent(id);view.innerHTML='<div class="admin-content-head"><div><strong>'+rows.length+' registros carregados</strong><small>Somente leitura nesta etapa</small></div><input id="content-search" class="admin-search" placeholder="Pesquisar por título"></div><div id="content-list" class="admin-table">'+rows.map(row=>rowHTML(row,id)).join("")+'</div>';const search=document.getElementById("content-search");search.oninput=()=>{const q=search.value.toLowerCase();document.querySelectorAll("[data-search-row]").forEach(r=>r.hidden=!r.dataset.searchRow.includes(q))};if(id==="dossies")document.getElementById("content-list").onclick=e=>{const row=e.target.closest('[data-type="dossies"]');if(row){title.textContent="Editar dossiê";openDossierEditor(row.dataset.id,view).catch(err=>view.innerHTML='<div class="admin-notice">'+esc(err.message)+'</div>')}}}catch(e){view.innerHTML='<div class="admin-notice">Falha ao consultar '+esc(CONTENT[id].label)+': '+esc(e.message)+'</div>'}}
function rowHTML(r,type){const status=r.status_publicacao||r.status_caso||r.status||(r.recomendado?"Recomendado":"");const sub=r.categoria||r.subgenero||r.autor||r.tag||"";return '<article class="admin-row '+(type==="dossies"?'is-clickable':'')+'" data-id="'+esc(r.id)+'" data-type="'+esc(type)+'" data-search-row="'+esc((r.titulo||"").toLowerCase())+'"><div><strong>'+esc(r.titulo||"Sem título")+'</strong><small>'+esc(sub)+'</small></div><span class="admin-status">'+esc(status||"—")+'</span><time>'+date(r.updated_at||r.created_at)+'</time></article>'}
function placeholder(id){return '<div class="admin-placeholder"><strong>'+esc(LABELS[id])+'</strong><br><br>Módulo reservado. Será conectado após o núcleo editorial e as políticas específicas desta área serem validados.</div>'}
async function openView(id){document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===id));title.textContent=LABELS[id]||"Central Administrativa";history.replaceState(null,"","#"+id);if(id==="overview")return renderOverview();if(CONTENT[id])return renderContent(id);view.innerHTML=placeholder(id)}
function showPanel(){login.hidden=true;app.hidden=false;renderNav();document.getElementById("admin-v2-logout").onclick=async()=>{await signOut();location.reload()};openView(location.hash.slice(1)||"overview")}
document.getElementById("admin-v2-login-form").onsubmit=async e=>{e.preventDefault();const msg=document.getElementById("admin-v2-login-message"),btn=document.getElementById("admin-v2-login-button");btn.disabled=true;msg.textContent="Verificando acesso...";try{await loginAdmin(document.getElementById("admin-v2-email").value.trim(),document.getElementById("admin-v2-password").value);showPanel()}catch(err){msg.textContent=err.message||"Não foi possível entrar."}finally{btn.disabled=false}};
(async()=>{try{if(await requireAdmin())showPanel();}catch(e){document.getElementById("admin-v2-login-message").textContent=e.message}})();