import{getClient}from"./auth.js";
export const CONTENT={dossies:{table:"Casos",label:"Dossiês",fields:"id,titulo,categoria,status,status_publicacao,slug,updated_at,created_at"},garimpo:{table:"casos_diarios",label:"Garimpo Sombrio",fields:"id,titulo,categoria,status_caso,status_publicacao,slug,updated_at,created_at"},pericias:{table:"pericias",label:"Perícia",fields:"id,titulo,categoria,updated_at,created_at"},lendas:{table:"lendas",label:"Lendas",fields:"id,titulo,categoria,classificacao,status_publicacao,slug,updated_at,created_at"},creepypastas:{table:"creepypastas",label:"Creepypastas",fields:"id,titulo,subgenero,classificacao,status_publicacao,slug,updated_at,created_at"},biblioteca:{table:"livros",label:"Biblioteca",fields:"id,titulo,autor,tag,recomendado,created_at"}};
export async function listContent(type){const c=CONTENT[type];if(!c)throw new Error("Tipo de conteúdo inválido.");const{data,error}=await getClient().from(c.table).select(c.fields).order(c.table==="livros"?"created_at":"updated_at",{ascending:false}).limit(100);if(error)throw error;return data||[]}
export async function getDossier(id){const{data,error}=await getClient().from("Casos").select("*").eq("id",id).single();if(error)throw error;return data}
export async function saveAdminDraft({recordId,title,payload}){const c=getClient(),{data:{user}}=await c.auth.getUser();if(!user)throw new Error("Sessão expirada.");const draft_key="admin-v2:dossie:"+recordId;const body={user_id:user.id,draft_key,content_type:"dossie",record_id:String(recordId),title:title||"Rascunho sem título",payload,updated_at:new Date().toISOString()};const{data,error}=await c.from("admin_drafts").upsert(body,{onConflict:"user_id,draft_key"}).select().single();if(error)throw error;return data}
export async function getAdminDraft(recordId){const{data,error}=await getClient().from("admin_drafts").select("*").eq("draft_key","admin-v2:dossie:"+recordId).maybeSingle();if(error)throw error;return data}
async function count(table,filter){let q=getClient().from(table).select("*",{count:"exact",head:true});if(filter)q=q.eq(filter[0],filter[1]);const{count,error}=await q;if(error)throw error;return count||0}
export async function dashboardCounts(){const entries=await Promise.all(Object.entries(CONTENT).map(async([key,c])=>[key,await count(c.table)]));const drafts=await count("admin_drafts");const reports=await count("content_reports",["status","pending"]);const suggestions=await count("Sugestoes",["status","nova"]);return{content:Object.fromEntries(entries),drafts,reports,suggestions,total:entries.reduce((n,[,v])=>n+v,0)}}
export async function listV2DraftSources(){const{data,error}=await getClient().from("admin_drafts").select("record_id,title,payload,updated_at").eq("content_type","dossie").like("draft_key","admin-v2:dossie:%").order("updated_at",{ascending:false}).limit(100);if(error)throw error;return(data||[]).flatMap(row=>((row.payload?.editor_v2?.fontes_estruturadas)||[]).map(s=>({...s,content_id:row.record_id,content_title:row.title,draft_updated_at:row.updated_at})))}
export async function getV2ContentState(recordId){const{data,error}=await getClient().from("admin_v2_content_state").select("*").eq("content_type","dossie").eq("record_id",String(recordId)).maybeSingle();if(error)throw error;return data}
export async function getCurrentDossierStamp(recordId){const{data,error}=await getClient().from("Casos").select("id,updated_at,status_publicacao").eq("id",recordId).single();if(error)throw error;return data}
export async function setV2EditorialStatus(recordId,status,baseUpdatedAt){const c=getClient(),{data:{user}}=await c.auth.getUser();if(!user)throw new Error("Sessão expirada.");const body={content_type:"dossie",record_id:String(recordId),editorial_status:status,base_updated_at:baseUpdatedAt||null,updated_by:user.id,updated_at:new Date().toISOString()};const{data,error}=await c.from("admin_v2_content_state").upsert(body,{onConflict:"content_type,record_id"}).select().single();if(error)throw error;return data}
export async function createV2Version(recordId,status,payload,baseUpdatedAt){const c=getClient(),{data:{user}}=await c.auth.getUser();if(!user)throw new Error("Sessão expirada.");const{data:last,error:lastError}=await c.from("admin_v2_versions").select("version_number").eq("content_type","dossie").eq("record_id",String(recordId)).order("version_number",{ascending:false}).limit(1);if(lastError)throw lastError;const version=(last?.[0]?.version_number||0)+1;const{data,error}=await c.from("admin_v2_versions").insert({content_type:"dossie",record_id:String(recordId),version_number:version,editorial_status:status,payload,base_updated_at:baseUpdatedAt||null,created_by:user.id}).select().single();if(error)throw error;return data}
export async function listV2Versions(recordId){const{data,error}=await getClient().from("admin_v2_versions").select("id,version_number,editorial_status,base_updated_at,created_at,created_by").eq("content_type","dossie").eq("record_id",String(recordId)).order("version_number",{ascending:false}).limit(30);if(error)throw error;return data||[]}
export async function getV2Version(versionId){const{data,error}=await getClient().from("admin_v2_versions").select("*").eq("id",versionId).single();if(error)throw error;return data}

export async function listReviewQueue(){const{data:states,error}=await getClient().from("admin_v2_content_state").select("*").in("editorial_status",["em_revisao","pronto"]).order("updated_at",{ascending:false});if(error)throw error;const ids=(states||[]).filter(x=>x.content_type==="dossie").map(x=>Number(x.record_id)).filter(Number.isFinite);let titles={};if(ids.length){const{data:rows,error:e}=await getClient().from("Casos").select("id,titulo,categoria,updated_at").in("id",ids);if(e)throw e;titles=Object.fromEntries((rows||[]).map(x=>[String(x.id),x]))}return(states||[]).map(s=>({...s,content:titles[s.record_id]||null}))}
export async function listReviewNotes(recordId){const{data,error}=await getClient().from("admin_v2_review_notes").select("*").eq("content_type","dossie").eq("record_id",String(recordId)).order("created_at",{ascending:false});if(error)throw error;return data||[]}
export async function addReviewNote(recordId,noteType,body){const c=getClient(),{data:{user}}=await c.auth.getUser();if(!user)throw new Error("Sessão expirada.");const{data,error}=await c.from("admin_v2_review_notes").insert({content_type:"dossie",record_id:String(recordId),note_type:noteType,body:body.trim(),created_by:user.id}).select().single();if(error)throw error;return data}
export async function resolveReviewNote(noteId,resolved=true){const c=getClient(),{data:{user}}=await c.auth.getUser();if(!user)throw new Error("Sessão expirada.");const body=resolved?{resolved:true,resolved_by:user.id,resolved_at:new Date().toISOString()}:{resolved:false,resolved_by:null,resolved_at:null};const{data,error}=await c.from("admin_v2_review_notes").update(body).eq("id",noteId).select().single();if(error)throw error;return data}

export async function scheduleV2Content(recordId,iso,note=""){const c=getClient(),{data:{user}}=await c.auth.getUser();if(!user)throw new Error("Sessão expirada.");const{data,error}=await c.from("admin_v2_content_state").update({editorial_status:"agendado",scheduled_for:iso,schedule_timezone:"America/Sao_Paulo",schedule_status:"scheduled",schedule_note:note||null,scheduled_by:user.id,updated_by:user.id,updated_at:new Date().toISOString()}).eq("content_type","dossie").eq("record_id",String(recordId)).eq("editorial_status","pronto").select().maybeSingle();if(error)throw error;if(!data)throw new Error("Somente conteúdos com status Pronto podem ser agendados.");return data}
export async function cancelV2Schedule(recordId){const c=getClient(),{data:{user}}=await c.auth.getUser();if(!user)throw new Error("Sessão expirada.");const{data,error}=await c.from("admin_v2_content_state").update({editorial_status:"pronto",scheduled_for:null,schedule_status:"cancelled",updated_by:user.id,updated_at:new Date().toISOString()}).eq("content_type","dossie").eq("record_id",String(recordId)).eq("schedule_status","scheduled").select().maybeSingle();if(error)throw error;if(!data)throw new Error("Não há agendamento ativo para cancelar.");return data}
export async function listV2Schedules(){const{data,error}=await getClient().from("admin_v2_content_state").select("*").eq("schedule_status","scheduled").order("scheduled_for",{ascending:true});if(error)throw error;const ids=(data||[]).filter(x=>x.content_type==="dossie").map(x=>Number(x.record_id)).filter(Number.isFinite);let titles={};if(ids.length){const{data:rows,error:e}=await getClient().from("Casos").select("id,titulo,categoria").in("id",ids);if(e)throw e;titles=Object.fromEntries((rows||[]).map(x=>[String(x.id),x]))}return(data||[]).map(x=>({...x,content:titles[x.record_id]||null}))}

export async function preparePublicationJob(recordId,compiledPayload,validation,mode="manual",scheduledFor=null,versionId=null){const c=getClient(),{data:{user}}=await c.auth.getUser();if(!user)throw new Error("Sessão expirada.");const stamp=await getDossier(recordId);const previous={titulo:stamp.titulo,categoria:stamp.categoria,local:stamp.local,ano:stamp.ano,status:stamp.status,imagem:stamp.imagem,resumo:stamp.resumo,historia:stamp.historia,evidencias:stamp.evidencias,teorias:stamp.teorias,documentos:stamp.documentos,conteudo_blocos:stamp.conteudo_blocos,slug:stamp.slug,editor_version:stamp.editor_version,status_publicacao:stamp.status_publicacao};const{data,error}=await c.from("admin_v2_publication_jobs").insert({content_type:"dossie",record_id:String(recordId),version_id:versionId||null,mode,status:"prepared",scheduled_for:scheduledFor,base_updated_at:stamp.updated_at,compiled_payload:compiledPayload,previous_payload:previous,validation,requested_by:user.id}).select().single();if(error)throw error;return data}
export async function listPublicationJobs(recordId){const{data,error}=await getClient().from("admin_v2_publication_jobs").select("id,mode,status,scheduled_for,base_updated_at,validation,requested_at,executed_at,error_message").eq("content_type","dossie").eq("record_id",String(recordId)).order("requested_at",{ascending:false}).limit(20);if(error)throw error;return data||[]}

export async function getPublicationJob(jobId){const{data,error}=await getClient().from("admin_v2_publication_jobs").select("*").eq("id",jobId).single();if(error)throw error;return data}
export async function simulatePublicationJob(jobId){const job=await getPublicationJob(jobId);if(job.status!=="prepared")return{ok:false,reason:"Job não está no estado prepared.",job};const live=await getDossier(job.record_id);const base=job.base_updated_at?new Date(job.base_updated_at).getTime():null,current=live.updated_at?new Date(live.updated_at).getTime():null;const conflict=base!==current;const required=["titulo","slug","resumo"];const missing=required.filter(k=>!String(job.compiled_payload?.[k]??"").trim());return{ok:!conflict&&!missing.length,conflict,missing,job,live}}

export async function createDossierV2(){const c=getClient();const{data,error}=await c.from("Casos").insert({titulo:"Novo dossiê",categoria:"",local:"",ano:"",status:"EM ANÁLISE",imagem:"",resumo:"",historia:"",evidencias:[],teorias:[],documentos:[],conteudo_blocos:[],editor_version:2,status_publicacao:"rascunho"}).select("*").single();if(error)throw error;return data}

export async function getGarimpo(id){const{data,error}=await getClient().from("casos_diarios").select("*").eq("id",id).single();if(error)throw error;return data}
export async function createGarimpoV2(){const slug="novo-registro-"+Date.now().toString(36);const{data,error}=await getClient().from("casos_diarios").insert({titulo:"Novo registro",slug,categoria:"GARIMPO SOMBRIO",status_caso:"EM INVESTIGAÇÃO",resumo:"Rascunho em elaboração.",conteudo:"Rascunho em elaboração.",evidencias:[],hipoteses:[],imagens:[],fontes:[],status_publicacao:"rascunho"}).select("*").single();if(error)throw error;return data}
export async function getGarimpoDraft(recordId){const c=getClient(),{data:{user}}=await c.auth.getUser();if(!user)return null;const{data,error}=await c.from("admin_drafts").select("*").eq("user_id",user.id).eq("draft_key","garimpo-v2:"+recordId).maybeSingle();if(error)throw error;return data}
export async function saveGarimpoDraft(recordId,title,payload){const c=getClient(),{data:{user}}=await c.auth.getUser();if(!user)throw new Error("Sessão expirada.");const{data,error}=await c.from("admin_drafts").upsert({user_id:user.id,draft_key:"garimpo-v2:"+recordId,content_type:"caso_diario",record_id:String(recordId),title:title||"Rascunho sem título",payload,updated_at:new Date().toISOString()},{onConflict:"user_id,draft_key"}).select().single();if(error)throw error;return data}
