import{getDossier,getAdminDraft,saveAdminDraft}from"./data.js";import{uploadMedia}from"./media.js";
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
let current=null,timer=null,working={};
const BLOCK_TYPES={paragrafo:"Parágrafo",subtitulo:"Subtítulo",imagem:"Imagem",galeria:"Galeria",documento:"Documento",citacao:"Citação",nota_do_arquivo:"Nota do Arquivo",video:"Vídeo",separador:"Separador",destaque:"Destaque"};
function uid(){return"v2-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,7)}
function normalizeBlocks(list){return(Array.isArray(list)?list:[]).map((b,i)=>({...b,id:b.id||uid(),tipo:b.tipo||"paragrafo",dados:b.dados&&typeof b.dados==="object"?{...b.dados}:{},ordem:i+1}))}
function syncBlocksFromDOM(){const root=document.getElementById("block-builder");if(!root)return;working.conteudo_blocos=[...root.querySelectorAll(".block-card")].map((card,i)=>{const old=working.conteudo_blocos.find(x=>String(x.id)===card.dataset.id)||{};const dados={...(old.dados||{})};card.querySelectorAll("[data-block-field]").forEach(el=>dados[el.dataset.blockField]=el.type==="checkbox"?el.checked:el.value);return{...old,id:card.dataset.id,tipo:card.dataset.type,dados,ordem:i+1}})}
function blockFields(b){const d=b.dados||{},t=b.tipo;if(t==="separador")return'<div class="block-empty">Separador visual</div>';if(t==="imagem")return'<div class="block-media-upload"><input type="file" accept="image/*" data-block-file><button type="button" data-block-upload>Enviar imagem</button><span data-block-upload-state></span></div><label>URL da imagem<input data-block-field="url" value="'+esc(d.url||d.src||"")+'"></label><label>Legenda<input data-block-field="legenda" value="'+esc(d.legenda||"")+'"></label><label>Crédito<input data-block-field="credito" value="'+esc(d.credito||"")+'"></label><label>Fonte<input data-block-field="fonte" value="'+esc(d.fonte||"")+'"></label><label class="block-check"><input type="checkbox" data-block-field="sensivel" '+(d.sensivel?"checked":"")+'> Conteúdo sensível</label>';if(t==="video")return'<label>URL do vídeo<input data-block-field="url" value="'+esc(d.url||"")+'"></label><label>Legenda<input data-block-field="legenda" value="'+esc(d.legenda||"")+'"></label>';if(t==="documento")return'<label>Título<input data-block-field="titulo" value="'+esc(d.titulo||"")+'"></label><label>URL/documento<input data-block-field="url" value="'+esc(d.url||"")+'"></label><label>Descrição<textarea data-block-field="descricao" rows="4">'+esc(d.descricao||"")+'</textarea></label>';return'<label>Texto<textarea data-block-field="texto" rows="'+(t==="paragrafo"?8:4)+'">'+esc(d.texto||"")+'</textarea></label>'}
function blockCard(b,i){return'<article class="block-card" draggable="true" data-id="'+esc(b.id)+'" data-type="'+esc(b.tipo)+'"><header><span class="block-grip" title="Arrastar para reordenar">⋮⋮</span><strong>'+(BLOCK_TYPES[b.tipo]||esc(b.tipo))+'</strong><small>#'+(i+1)+'</small><div><button type="button" data-block-up>↑</button><button type="button" data-block-down>↓</button><button type="button" data-block-delete>Excluir</button></div></header><div class="block-fields">'+blockFields(b)+'</div></article>'}
function renderBlockBuilder(){working.conteudo_blocos=normalizeBlocks(working.conteudo_blocos);const root=document.getElementById("block-builder");if(!root)return;root.innerHTML=working.conteudo_blocos.map(blockCard).join("")||'<div class="block-empty">Nenhum bloco estruturado.</div>';bindBlocks(root)}
function bindBlocks(root){root.querySelectorAll("[data-block-field]").forEach(el=>el.addEventListener("input",()=>{syncBlocksFromDOM();scheduleAutosave()}));root.onclick=async e=>{const card=e.target.closest(".block-card");if(!card)return;if(e.target.closest("[data-block-upload]")){const file=card.querySelector("[data-block-file]").files[0],state=card.querySelector("[data-block-upload-state]");if(!file)return state.textContent="Selecione uma imagem.";state.textContent="Enviando...";try{const m=await uploadMedia(file,{kind:"imagem",contentId:"dossies/"+current.id+"/blocos"});card.querySelector('[data-block-field="url"]').value=m.url;state.textContent="Enviado.";syncBlocksFromDOM();scheduleAutosave()}catch(err){state.textContent="Falha: "+err.message}return}syncBlocksFromDOM();const i=working.conteudo_blocos.findIndex(x=>String(x.id)===card.dataset.id);if(e.target.closest("[data-block-delete]"))working.conteudo_blocos.splice(i,1);else if(e.target.closest("[data-block-up]")&&i>0)[working.conteudo_blocos[i-1],working.conteudo_blocos[i]]=[working.conteudo_blocos[i],working.conteudo_blocos[i-1]];else if(e.target.closest("[data-block-down]")&&i<working.conteudo_blocos.length-1)[working.conteudo_blocos[i+1],working.conteudo_blocos[i]]=[working.conteudo_blocos[i],working.conteudo_blocos[i+1]];else return;renderBlockBuilder();scheduleAutosave()};let dragged=null;root.ondragstart=e=>{dragged=e.target.closest(".block-card");if(dragged)dragged.classList.add("dragging")};root.ondragend=()=>{if(dragged)dragged.classList.remove("dragging");dragged=null};root.ondragover=e=>{e.preventDefault();const target=e.target.closest(".block-card");if(!dragged||!target||dragged===target)return;const box=target.getBoundingClientRect();root.insertBefore(dragged,e.clientY<box.top+box.height/2?target:target.nextSibling)};root.ondrop=e=>{e.preventDefault();syncBlocksFromDOM();working.conteudo_blocos=normalizeBlocks(working.conteudo_blocos);renderBlockBuilder();scheduleAutosave()}}
function addBlock(type){syncBlocksFromDOM();working.conteudo_blocos.push({id:uid(),tipo:type,dados:{texto:""},ordem:working.conteudo_blocos.length+1});renderBlockBuilder();scheduleAutosave()}
function normalizeDocs(list){return(Array.isArray(list)?list:[]).map((d,i)=>typeof d==="string"?{id:uid(),titulo:"Documento "+(i+1),url:d,descricao:"",fonte:"",credito:"",sensivel:false}:({...d,id:d.id||uid()}))}
function syncDocs(){const root=document.getElementById("document-builder");if(!root)return;working.documentos=[...root.querySelectorAll(".document-card")].map(card=>{const old=working.documentos.find(x=>String(x.id)===card.dataset.id)||{};const out={...old,id:card.dataset.id};card.querySelectorAll("[data-doc-field]").forEach(el=>out[el.dataset.docField]=el.type==="checkbox"?el.checked:el.value);return out})}
function docCard(d,i){return'<article class="document-card" data-id="'+esc(d.id)+'"><header><strong>Documento '+(i+1)+'</strong><div><button type="button" data-doc-up>↑</button><button type="button" data-doc-down>↓</button><button type="button" data-doc-remove>Remover vínculo</button></div></header><div class="document-fields"><label>Título<input data-doc-field="titulo" value="'+esc(d.titulo||d.nome||"")+'"></label><label>URL do arquivo<input data-doc-field="url" value="'+esc(d.url||d.link||"")+'"></label><label class="wide">Descrição<textarea data-doc-field="descricao" rows="4">'+esc(d.descricao||"")+'</textarea></label><label>Fonte<input data-doc-field="fonte" value="'+esc(d.fonte||"")+'"></label><label>Crédito<input data-doc-field="credito" value="'+esc(d.credito||"")+'"></label><label>URL da fonte<input data-doc-field="fonte_url" value="'+esc(d.fonte_url||"")+'"></label><label>Tipo/documento<input data-doc-field="tipo" value="'+esc(d.tipo||"")+'"></label><label class="doc-check"><input type="checkbox" data-doc-field="sensivel" '+(d.sensivel?"checked":"")+'> Documento sensível</label></div></article>'}
function renderDocs(){working.documentos=normalizeDocs(working.documentos);const root=document.getElementById("document-builder");if(!root)return;root.innerHTML=working.documentos.map(docCard).join("")||'<div class="block-empty">Nenhum documento vinculado.</div>';root.querySelectorAll("[data-doc-field]").forEach(el=>el.addEventListener("input",()=>{syncDocs();scheduleAutosave()}));root.onclick=e=>{const card=e.target.closest(".document-card");if(!card)return;syncDocs();const i=working.documentos.findIndex(x=>String(x.id)===card.dataset.id);if(e.target.closest("[data-doc-remove]"))working.documentos.splice(i,1);else if(e.target.closest("[data-doc-up]")&&i>0)[working.documentos[i-1],working.documentos[i]]=[working.documentos[i],working.documentos[i-1]];else if(e.target.closest("[data-doc-down]")&&i<working.documentos.length-1)[working.documentos[i+1],working.documentos[i]]=[working.documentos[i],working.documentos[i+1]];else return;renderDocs();scheduleAutosave()}}
async function uploadDocument(){const input=document.getElementById("document-file"),state=document.getElementById("document-upload-state"),file=input?.files?.[0];if(!file)return state.textContent="Selecione um documento.";state.textContent="Enviando...";try{const m=await uploadMedia(file,{kind:"documento",contentId:"dossies/"+current.id});working.documentos=normalizeDocs(working.documentos);working.documentos.push({id:uid(),titulo:file.name,url:m.url,descricao:"",fonte:"",credito:"",fonte_url:"",tipo:file.type||"documento",sensivel:false,storage_path:m.path,bucket:m.bucket});renderDocs();state.textContent="Documento enviado e vinculado ao rascunho.";scheduleAutosave()}catch(e){state.textContent="Falha: "+e.message}}
const value=id=>document.getElementById(id)?.value??"";
const parseLines=id=>value(id).split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean);
const jsonText=x=>JSON.stringify(x??[],null,2);
function payload(){return{...working,titulo:value("ed-titulo"),categoria:value("ed-categoria"),local:value("ed-local"),ano:value("ed-ano"),status:value("ed-status"),imagem:value("ed-imagem"),resumo:value("ed-resumo"),historia:value("ed-historia"),evidencias:parseLines("ed-evidencias"),teorias:parseLines("ed-teorias"),documentos:document.getElementById("document-builder")?(syncDocs(),working.documentos||[]):working.documentos||[],conteudo_blocos:document.getElementById("block-builder")?(syncBlocksFromDOM(),working.conteudo_blocos||[]):working.conteudo_blocos||[],slug:value("ed-slug"),status_publicacao:current?.status_publicacao||"rascunho",base_updated_at:current?.updated_at||null,editor_v2:{fontes:value("ed-fontes"),seo_title:value("ed-seo-title"),seo_description:value("ed-seo-description"),pessoas:value("ed-pessoas"),notas_internas:value("ed-notas"),cover_caption:value("ed-cover-caption"),cover_credit:value("ed-cover-credit"),cover_source:value("ed-cover-source"),cover_source_url:value("ed-cover-source-url"),cover_alt:value("ed-cover-alt")}}}
function safeJSON(s,fallback){try{return JSON.parse(s)}catch{return fallback}}
function setMessage(t){const el=document.getElementById("editor-save-state");if(el)el.textContent=t}
async function save(){if(!current)return;setMessage("Salvando rascunho...");try{working=payload();await saveAdminDraft({recordId:current.id,title:value("ed-titulo"),payload:working});setMessage("Rascunho V2 salvo · "+new Date().toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"}))}catch(e){setMessage("Falha ao salvar rascunho: "+e.message)}}
function scheduleAutosave(){clearTimeout(timer);setMessage("Alterações não salvas");timer=setTimeout(save,1200)}
function preview(){const p=payload();document.getElementById("editor-preview").innerHTML='<div class="preview-paper"><small>PRÉ-VISUALIZAÇÃO INTERNA</small><h2>'+esc(p.titulo||"Sem título")+'</h2><p class="preview-meta">'+esc([p.categoria,p.local,p.ano,p.status].filter(Boolean).join(" · "))+'</p><p class="preview-lead">'+esc(p.resumo)+'</p><div class="preview-story">'+esc(p.historia).replace(/\n\n+/g,"</p><p>").replace(/^/,"<p>").replace(/$/,"</p>")+'</div><h3>Evidências</h3>'+p.evidencias.map(x=>'<p>'+esc(x)+'</p>').join("")+'<h3>Teorias e interpretações</h3>'+p.teorias.map(x=>'<p>'+esc(x)+'</p>').join("")+'</div>';document.getElementById("editor-preview").hidden=false}
const tabs=[
["geral","Geral"],["conteudo","Conteúdo"],["evidencias","Evidências"],["teorias","Teorias"],["midia","Mídia"],["fontes","Fontes"],["seo","SEO"],["interno","Interno"],["publicacao","Publicação"]
];
function section(id,d){const extra=d.editor_v2||{};const map={
geral:'<label class="wide">Título<input id="ed-titulo" value="'+esc(d.titulo)+'"></label><label>Categoria<input id="ed-categoria" value="'+esc(d.categoria)+'"></label><label>Status do caso<input id="ed-status" value="'+esc(d.status)+'"></label><label>Local<input id="ed-local" value="'+esc(d.local)+'"></label><label>Ano/período<input id="ed-ano" value="'+esc(d.ano)+'"></label><label class="wide">Resumo<textarea id="ed-resumo" rows="6">'+esc(d.resumo)+'</textarea></label><label class="wide">Slug<input id="ed-slug" value="'+esc(d.slug)+'" readonly></label>',
conteudo:'<label class="wide">História completa <small>Campo legado preservado para compatibilidade com o site atual.</small><textarea id="ed-historia" rows="16">'+esc(d.historia)+'</textarea></label><div class="wide block-toolbar"><div><strong>Construtor de blocos</strong><small>Arraste, use as setas ou adicione novos elementos.</small></div><select id="new-block-type"><option value="paragrafo">Parágrafo</option><option value="subtitulo">Subtítulo</option><option value="imagem">Imagem</option><option value="galeria">Galeria</option><option value="documento">Documento</option><option value="citacao">Citação</option><option value="nota_do_arquivo">Nota do Arquivo</option><option value="video">Vídeo</option><option value="separador">Separador</option><option value="destaque">Destaque</option></select><button type="button" id="add-block">Adicionar bloco</button></div><div id="block-builder" class="block-builder wide"></div>',
evidencias:'<label class="wide">Evidências <small>Separe cada card com uma linha em branco.</small><textarea id="ed-evidencias" rows="18">'+esc((d.evidencias||[]).join("\n\n"))+'</textarea></label>',
teorias:'<label class="wide">Teorias e interpretações <small>Separe cada card com uma linha em branco.</small><textarea id="ed-teorias" rows="18">'+esc((d.teorias||[]).join("\n\n"))+'</textarea></label>',
midia:'<div class="media-upload wide"><div><strong>Capa do dossiê</strong><small>Envie uma imagem diretamente ou mantenha a URL atual.</small></div><input id="cover-file" type="file" accept="image/*"><button type="button" id="upload-cover">Enviar capa</button><span id="cover-upload-state"></span></div><label class="wide">URL da capa<input id="ed-imagem" value="'+esc(d.imagem)+'"></label><div id="cover-preview" class="media-preview wide">'+(d.imagem?'<img src="'+esc(d.imagem)+'" alt="">':'Sem capa')+'</div><div class="media-meta wide"><label>Legenda<input id="ed-cover-caption" value="'+esc(extra.cover_caption)+'"></label><label>Crédito<input id="ed-cover-credit" value="'+esc(extra.cover_credit)+'"></label><label>Fonte<input id="ed-cover-source" value="'+esc(extra.cover_source)+'"></label><label>URL da fonte<input id="ed-cover-source-url" value="'+esc(extra.cover_source_url)+'"></label><label class="wide">Alt text<input id="ed-cover-alt" value="'+esc(extra.cover_alt)+'"></label></div><div class="document-section wide"><div class="document-upload"><div><strong>Acervo documental</strong><small>PDFs, decisões, relatórios, mapas, recortes e outros documentos.</small></div><input id="document-file" type="file" accept=".pdf,.doc,.docx,.txt,.rtf,image/*,application/pdf"><button type="button" id="upload-document">Enviar documento</button><span id="document-upload-state"></span></div><div id="document-builder" class="document-builder"></div></div>',
fontes:'<label class="wide">Fontes do V2 <small>Uma por linha no formato Nome da fonte | link completo. Este campo permanece apenas no rascunho até criarmos a estrutura aditiva de fontes.</small><textarea id="ed-fontes" rows="18">'+esc(extra.fontes)+'</textarea></label>',
seo:'<label class="wide">Título SEO<input id="ed-seo-title" value="'+esc(extra.seo_title)+'"></label><label class="wide">Meta descrição<textarea id="ed-seo-description" rows="6">'+esc(extra.seo_description)+'</textarea></label><div class="editor-info wide">O slug atual permanece protegido. Canonical, imagem social e indexação serão adicionados quando o modelo SEO for criado no banco.</div>',
interno:'<label class="wide">Pessoas relacionadas<textarea id="ed-pessoas" rows="10">'+esc(extra.pessoas)+'</textarea></label><label class="wide">Notas administrativas internas<textarea id="ed-notas" rows="12">'+esc(extra.notas_internas)+'</textarea></label>',
publicacao:'<div class="editor-info wide"><strong>Status editorial atual:</strong> '+esc(current.status_publicacao||"—")+'<br><br>O V2 já reserva Rascunho → Em revisão → Pronto → Agendado → Publicado → Arquivado. Agendamento e publicação continuarão bloqueados até a migração editorial ser validada.</div>'
};return map[id]}
function renderSection(id){working=payload();const form=document.getElementById("dossier-editor");form.innerHTML=section(id,working);document.querySelectorAll(".editor-tabs button").forEach(b=>b.classList.toggle("active",b.dataset.tab===id));form.querySelectorAll("input:not([readonly]),textarea").forEach(el=>{if(!el.hasAttribute("data-block-field"))el.addEventListener("input",scheduleAutosave)});if(id==="conteudo"){renderBlockBuilder();document.getElementById("add-block").onclick=()=>addBlock(document.getElementById("new-block-type").value)}if(id==="midia"){bindMedia();renderDocs();document.getElementById("upload-document").onclick=uploadDocument}}
async function bindMedia(){const btn=document.getElementById("upload-cover");if(!btn)return;btn.onclick=async()=>{const file=document.getElementById("cover-file").files[0],state=document.getElementById("cover-upload-state");if(!file)return state.textContent="Selecione uma imagem.";btn.disabled=true;state.textContent="Enviando...";try{const m=await uploadMedia(file,{kind:"imagem",contentId:"dossies/"+current.id});document.getElementById("ed-imagem").value=m.url;document.getElementById("cover-preview").innerHTML='<img src="'+esc(m.url)+'" alt="">';state.textContent="Upload concluído.";scheduleAutosave()}catch(e){state.textContent="Falha: "+e.message}finally{btn.disabled=false}}}
export async function openDossierEditor(id,container){container.innerHTML='<div class="admin-placeholder">Abrindo editor seguro...</div>';const[record,draft]=await Promise.all([getDossier(id),getAdminDraft(id)]);current=record;working=draft?.payload||structuredClone(record);working.editor_v2=working.editor_v2||{};container.innerHTML='<div class="editor-shell"><div class="editor-warning"><strong>Editor V2 em teste.</strong> Todos os campos desta tela salvam somente em <code>admin_drafts</code>. O registro público permanece intacto.</div><div class="editor-tabs">'+tabs.map(([id,label])=>'<button data-tab="'+id+'" class="'+(id==="geral"?"active":"")+'">'+label+'</button>').join("")+'</div><form id="dossier-editor" class="editor-form"></form><div id="editor-preview" class="editor-preview" hidden></div><div class="editor-bottom"><span id="editor-save-state">'+(draft?"Rascunho V2 recuperado":"Nenhuma alteração no V2")+'</span><div><button id="btn-draft" class="secondary">Salvar rascunho</button><button id="btn-preview" class="secondary">Visualizar</button><button id="btn-schedule" disabled>Agendar</button><button id="btn-publish" disabled>Publicar</button></div></div></div>';renderSection("geral");container.querySelector(".editor-tabs").onclick=e=>{const b=e.target.closest("[data-tab]");if(b)renderSection(b.dataset.tab)};document.getElementById("btn-draft").onclick=save;document.getElementById("btn-preview").onclick=preview;return record}