import{getDossier,getAdminDraft,saveAdminDraft}from"./data.js";
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
let current=null,timer=null;
function value(id){return document.getElementById(id)?.value??""}
function payload(){return{titulo:value("ed-titulo"),categoria:value("ed-categoria"),local:value("ed-local"),ano:value("ed-ano"),status:value("ed-status"),resumo:value("ed-resumo"),historia:value("ed-historia"),slug:value("ed-slug"),status_publicacao:current?.status_publicacao||"rascunho",base_updated_at:current?.updated_at||null}}
function setMessage(t){const el=document.getElementById("editor-save-state");if(el)el.textContent=t}
async function save(){if(!current)return;setMessage("Salvando rascunho...");try{await saveAdminDraft({recordId:current.id,title:value("ed-titulo"),payload:payload()});setMessage("Rascunho V2 salvo · "+new Date().toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"}) )}catch(e){setMessage("Falha ao salvar rascunho: "+e.message)}}
function scheduleAutosave(){clearTimeout(timer);setMessage("Alterações não salvas");timer=setTimeout(save,1200)}
function preview(){const p=payload();document.getElementById("editor-preview").innerHTML='<div class="preview-paper"><small>PRÉ-VISUALIZAÇÃO INTERNA</small><h2>'+esc(p.titulo||"Sem título")+'</h2><p class="preview-meta">'+esc([p.categoria,p.local,p.ano,p.status].filter(Boolean).join(" · "))+'</p><p class="preview-lead">'+esc(p.resumo)+'</p><div class="preview-story">'+esc(p.historia).replace(/\n\n+/g,"</p><p>").replace(/^/,"<p>").replace(/$/,"</p>")+'</div></div>';document.getElementById("editor-preview").hidden=false}
export async function openDossierEditor(id,container){container.innerHTML='<div class="admin-placeholder">Abrindo editor seguro...</div>';const [record,draft]=await Promise.all([getDossier(id),getAdminDraft(id)]);current=record;const d=draft?.payload||record;container.innerHTML='<div class="editor-shell"><div class="editor-warning"><strong>Editor V2 em teste.</strong> Salvar rascunho grava apenas em <code>admin_drafts</code>. O dossiê público não é alterado.</div><div class="editor-tabs"><button class="active">Geral</button><button disabled>Conteúdo</button><button disabled>Cronologia</button><button disabled>Evidências</button><button disabled>Teorias</button><button disabled>Pessoas</button><button disabled>Mídia</button><button disabled>Fontes</button><button disabled>SEO</button><button disabled>Publicação</button></div><form id="dossier-editor" class="editor-form"><label class="wide">Título<input id="ed-titulo" value="'+esc(d.titulo)+'"></label><label>Categoria<input id="ed-categoria" value="'+esc(d.categoria)+'"></label><label>Status do caso<input id="ed-status" value="'+esc(d.status)+'"></label><label>Local<input id="ed-local" value="'+esc(d.local)+'"></label><label>Ano/período<input id="ed-ano" value="'+esc(d.ano)+'"></label><label class="wide">Resumo<textarea id="ed-resumo" rows="5">'+esc(d.resumo)+'</textarea></label><label class="wide">História<textarea id="ed-historia" rows="18">'+esc(d.historia)+'</textarea></label><label class="wide">Slug<input id="ed-slug" value="'+esc(d.slug)+'" readonly></label></form><div id="editor-preview" class="editor-preview" hidden></div><div class="editor-bottom"><span id="editor-save-state">'+(draft?"Rascunho V2 recuperado":"Nenhuma alteração no V2")+'</span><div><button id="btn-draft" class="secondary">Salvar rascunho</button><button id="btn-preview" class="secondary">Visualizar</button><button id="btn-schedule" disabled title="Será habilitado após validação da escrita editorial">Agendar</button><button id="btn-publish" disabled title="Será habilitado após validação da escrita editorial">Publicar</button></div></div></div>';
container.querySelectorAll("#dossier-editor input:not([readonly]),#dossier-editor textarea").forEach(el=>el.addEventListener("input",scheduleAutosave));document.getElementById("btn-draft").onclick=save;document.getElementById("btn-preview").onclick=preview;return record}